import board
import neopixel
import os

PIXEL_PIN = board.D5
BUTTON_PIN = board.BUTTON
INBUILT_NEOPIXEL_PIN = board.NEOPIXEL_I2C_POWER
BATTERY_PIN = board.VOLTAGE_MONITOR

ORDER = neopixel.RGB

SSID_NAME = os.getenv("SSID_NAME")
SSID_PASS = os.getenv("WLAN_PASS")
NUM_PIXELS = 10
MODE_FORM_KEY = "mode"
MODE_RAINBOW = "rainbow_mode"
MODE_SLEEP = "sleep"
MODE_COLOR_PULSE = "color_pulse_mode"
RESET_VARS_FORM_KEY = "reset_variables"
SETTINGS_URL = "/settings"
RAINBOW_SETTINGS_URL = "/settings/rainbow"
COLOR_PULSE_SETTINGS_URL = "/settings/color_pulse"

TARGET_LOOP_RATE = 60  # hz
TARGET_LOOP_SECONDS = 1 / TARGET_LOOP_RATE

BRIGHTNESS_LOWER_BOUND = 0.0
BRIGHTNESS_UPPER_BOUND = 1.0
BRIGHTNESS_FORM_KEY = "brightness"
RAINBOW_MIN_SPEED = 0
RAINBOW_MAX_SPEED = 0.1
RAINBOW_SPEED_FORM_KEY = "rainbow_speed"

COLOR_R_FORM_KEY = "r"
COLOR_G_FORM_KEY = "g"
COLOR_B_FORM_KEY = "b"
COLOR_UPPER_BOUND = 255
COLOR_LOWER_BOUND = 0

RED_COLOR_KEY = "red_color"
RED_COLOR = (255, 0, 0)
ORANGE_COLOR_KEY = "orange_color"
ORANGE_COLOR = (255, 40, 0)
YELLOW_COLOR_KEY = "yellow_color"
YELLOW_COLOR = (255, 160, 0)
GREEN_COLOR_KEY = "green_color"
GREEN_COLOR = (0, 255, 0)
BLUE_COLOR_KEY = "blue_color"
BLUE_COLOR = (0, 0, 255)
PURPLE_COLOR_KEY = "purple_color"
PURPLE_COLOR = (255, 0, 255)
COLOR_PULSE_INTERVAL_KEY = "color_pulse_interval"
COLOR_PULSE_INTERVAL_MINIMUM = 0
COLOR_PULSE_INTERVAL_MAXIMUM = 20
PRESET_COLORS = {RED_COLOR_KEY: RED_COLOR, ORANGE_COLOR_KEY: ORANGE_COLOR,
                 YELLOW_COLOR_KEY: YELLOW_COLOR, GREEN_COLOR_KEY: GREEN_COLOR,
                 BLUE_COLOR_KEY: BLUE_COLOR, PURPLE_COLOR_KEY: PURPLE_COLOR}
PULSE_BRIGHTNESS_PERCENT_KEY = "pulse_brightness_percent"
PULSE_BRIGHTNESS_PCT_MINIMUM = 0
PULSE_BRIGHTNESS_PCT_MAXIMUM = 1